---
version: 0.2
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

runson: linux

autosplit: true
retryOnFailure: true

maxRetries: 1
concurrency: 2

#pre:
#  # Skip execution of the tests in the pre step
#  - mvn dependency:resolve

post:
  - ls target/surefire-reports/

mergeArtifacts: true


uploadArtefacts:
 - name: ExecutionSnapshots
   path:
    - target/surefire-reports/html/**

framework:
  name: maven/testng
  defaultReports: false
  flags:
    - "-Dsuite=api"