---
version: 0.2
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

runson: linux

runtime:
  - language: java
    version: '17'

autosplit: true
retryOnFailure: true

maxRetries: 1
concurrency: 1

preDirectives:
  commands: 
    - cat /proc/mounts
    - export
    - export TERM="xterm" && export && top -b -n 1
    - uname -a
    - apt-get update && apt-get install -y htop && { sleep 5; killall htop; exit; } ;; htop -C

#pre:
#  # Skip execution of the tests in the pre step
#  - mvn dependency:resolve

post:
  - ls target/surefire-reports/

mergeArtifacts: true


#uploadArtefacts:
# - name: ExecutionSnapshots
#   path:
#    - target/surefire-reports/**

framework:
  name: maven/testng
  defaultReports: true
  flags:
    - "-Dsuite=api"