---
version: 0.2
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150

runson: linux

runtime:
  - language: java
    version: '17'

autosplit: true
retryOnFailure: true

maxRetries: 1
concurrency: 2

preDirectives:
  commands: 
    - cat /proc/mounts  | grep -E -w '(cpu|memory)'
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us
    - cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us
    - cat /sys/fs/cgroup/cpu,cpuacct/cpu.shares
    - export
    - top -n 1
#pre:
#  # Skip execution of the tests in the pre step
#  - mvn dependency:resolve

post:
  - ls target/surefire-reports/

mergeArtifacts: true


uploadArtefacts:
 - name: ExecutionSnapshots
   path:
    - target/surefire-reports/**

framework:
  name: maven/testng
  defaultReports: true
  flags:
    - "-Dsuite=api"